### ISSUE TITLE
一定要使用ray么？

### ISSUE THREAD

**Issue by zstbackcourt** [llan-ml/tesp#1]
请问一定要使用ray么？如果不使用ray应该如何运行脚本？ray对整个实验加速有多快呢？

**Comment by zstbackcourt** [comment]
或者说，你这个ray该如何部署？我看了一下你的.sh脚本，似乎环境和ip端口什么的都是固定了的

**Comment by zstbackcourt** [comment]
(venv) amax@Venus:~/MetaRLProject/tesp$ sh update_ray_codes.sh 
update_ray_codes.sh: 3: update_ray_codes.sh: source: not found
update_ray_codes.sh: 5: update_ray_codes.sh: pushd: not found
update_ray_codes.sh: 10: update_ray_codes.sh: popd: not found
请问这个问题该如何解决

**Comment by llan-ml** [comment]
Hi @zstbackcourt . Meta-RL在训练时每次迭代需要的样本数非常大，所以需要对不同的环境进行并行采样。之前大部分工作都是基于MPI进行分布式采样。我这里是基于Ray和RLlib的实现，是伯克利一个组主推的Python并行计算和强化学习的库。

这里我只是提供了一些参考的shell脚本，具体的部署可能得根据你们的自己的计算环境进行调整，比如说集群节点和文件目录的设置。

我用的环境是Ubuntu 16.04和bash，这三个命令找不到可能是因为你用的sh？

**Comment by zstbackcourt** [comment]
请问可以开源基于MPI的实验源码么？MPI的实验取得了和Ray一样的效果么？

**Comment by llan-ml** [comment]
不好意思，之前的话有歧义。我是说对于并行采样，之前工作（如，OpenAI baselines和MLSH）是用MPI实现的。我这里是基于Ray实现的。
