### ISSUE TITLE
KeyError: 'single_agent'

### ISSUE THREAD

**Issue by hyyh28** [llan-ml/tesp#6]
when I use the local mode to run the experiment, the error occurs:

  File "/home/hua/tesp/tesp/maml/maml.py", line 41, in on_episode_step
    "single_agent"].buffers["infos"][-1]["dist_reward"]
KeyError: 'single_agent'

Is there any wrong with the code?

**Comment by llan-ml** [comment]
@hyyh28 Which version of ray did you use? You should copy the code of Tune and RLlib in this repo into the ray package you installed.
